#!/usr/bin/env bash
if [ "$CODESPACES" = "true" ]; then
  # Source my dotfiles for zsh.
  echo "source /workspaces/.codespaces/.persistedshare/dotfiles/codespacesrc" >> $HOME/.zshrc
  
  # Add repo access to npmrc
  # https://github.com/customink/ndx/blob/da294f6eb1a66ec17509e434bbecb8ba80ed4fa8/docs/development.md#authentication-for-private-packages
  echo "//npm.pkg.github.com/:_authToken=${CI_GH_AUTH}" >> $HOME/.npmrc
  chmod 600 $HOME/.npmrc
fi
