#!/usr/bin/env bash
if [ "$CODESPACES" = "true" ]; then
  echo "In a Codespaces instance. Adding Codespaces-specific settings."

  # Source my dotfiles for zsh.
  echo "source /workspaces/.codespaces/.persistedshare/dotfiles/codespacesrc" >> $HOME/.zshrc

  # Add repo access to npmrc
  # https://github.com/customink/ndx/blob/da294f6eb1a66ec17509e434bbecb8ba80ed4fa8/docs/development.md#authentication-for-private-packages
  echo "//npm.pkg.github.com/:_authToken=${CI_GH_AUTH}" >> $HOME/.npmrc
  chmod 600 $HOME/.npmrc

  # Add repo access more generally
  cp /workspaces/.codespaces/.persistedshare/dotfiles/codespaces/netrc $HOME/.netrc
  sed -i -e "s/<auth>/${CI_GH_AUTH}/g" $HOME/.netrc
  chmod 600 $HOME/.netrc
fi
