#!/usr/bin/env bash
if [ "$CODESPACES" = "true" ]; then
  echo "In a Codespaces instance. Adding Codespaces-specific settings."

  # Source my dotfiles for zsh.
  echo "source /workspaces/.codespaces/.persistedshare/dotfiles/zsh/codespaces" >> $HOME/.zshrc
else
  echo "Copying main ZSH RC"
  cp ../zshrc $HOME/.zshrc

  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Looks like we're running on a Mac. Adding Mac-specific things."

    # This should detect if it's a work machine, based on an env variable set by Strap, which is how this is getting called
    if [ -n $CUSTOM_BREW_COMMAND ]; then
      echo "This machine is for work. Setting up work-specific things."

      echo "source ~/.dotfiles/zsh/work" >> $HOME/.zshrc
    else
      echo "Not a work machine. Setting up generic Mac stuff."

      echo "source ~/.dotfiles/zsh/darwin" >> ~/.zshrc
    fi
  fi
fi
